### PR TITLE
C/QotW+notable changes

### PR DESCRIPTION
**Pull request by llogiq**

### CODE REVIEW

**Comment by programmerjake** [comment]
I was under the impression that algebraics would be the crate-of-the-week since it has 6 votes to pin-project's 3 votes.

see also https://github.com/cmr/this-week-in-rust/pull/1014#issuecomment-535231476

**Comment by llogiq** [comment]
Oops, must have overlooked it. I'll change the PR.

**Comment by llogiq** [comment]
Ah, wait a minute: algebraics was suggested the week before, and lost out to texture-synthesis. That's why I didn't include it. We usually don't look into last week's suggestions. Feel free to re-suggest, though.

**Comment by nasa42** [comment]
I've renominated algebraics for next week. :+1:

**Comment by programmerjake** [comment]
> I've renominated algebraics for next week.

Ah, ok. Thanks!

**Pull request merged**
