### PR TITLE
note that `cargo clippy` has been released

### PR DESCRIPTION
**Pull request by oli-obk**
@llogiq @Manishearth is "annoying" too strong? I can't seem to find a good (english) word for what I want to say. Maybe "nagging"? I want it to sound positive, like "teaching".

### CODE REVIEW

**Comment by Manishearth** [comment]
No, we strive to be as annoying as possible

**Comment by Manishearth** [comment]
@llogiq, could you blog about this too? Your blog seems to have become the canonical "all things clippy" location :smile:

**Comment by llogiq** [comment]
Will do. But first I'll need to catch some sleep and get to my PC.

**Comment by Manishearth** [comment]
No problem, take your time :smile:

**Comment by nasa42** [comment]
Thanks for the PR @oli-obk!

**Pull request merged**
