### PR TITLE
No CotW, but a lot of notable changes

### PR DESCRIPTION
**Pull request by llogiq**
Despite having only slept for two hours last night, here's this week's changes.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
There were [a lot of nominations, actually](https://users.rust-lang.org/t/crate-of-the-week/2704/211):

* ruru
* Domafic
* peg

Or am I getting something wrong?

**Comment by llogiq** [comment]
Those were this week, not last week.

**Comment by matthiasbeyer** [comment]
ah, ok.

**Comment by nasa42** [comment]
> Despite having only slept for two hours last night, here's this week's changes.

Appreciate your continuous efforts :+1:

**Pull request merged**
