### PR TITLE
TWiR Release 96 (14 September 2015).

### PR DESCRIPTION
**Pull request by nasa42**
@brson @llogiq I've added a new section "Notable changes" where I plan to document well... "notable changes" in Rust core. However, of all the [79 PRs merged](https://github.com/issues?q=is%3Apr+org%3Arust-lang+is%3Amerged+merged%3A2015-09-07..2015-09-14), it is hard for me to pick "notable" ones, and someone who is more involved in the Rust core can certainly help me out here.
For this week, I've picked two PRs, however I'm not very sure about them. Please pay a closer attention to this section while reviewing my drafts, at least for next few weeks while I get more and more familiar with Rust progress flow.

### CODE REVIEW

**Comment by llogiq** [comment]
I think #28173 should be a notable change. Also  #28270. And the two you already have.

Btw. I'm a bit surprised to see my real name in the contributors list. Must be my global git config which includes name and email...

**Comment by nasa42** [comment]
*Comparison operators are now available for raw pointers*
Is it a good (and correct) heading for https://github.com/rust-lang/rust/pull/28270 ?

**Comment by nasa42** [comment]
s/operators/operations/

**Comment by llogiq** [comment]
Or "Comparing raw pointers no longer crashes".

**Comment by nasa42** [comment]
You are awesome! Now a better headline for https://github.com/rust-lang/rust/pull/28339 would be...?
My best try was - "These features have been marked as `stable` (or `deprecated`) for 1.4"
(pretty sure it sucks).

**Comment by llogiq** [comment]
Not too bad. Perhaps "Rust 1.4 deprecates some, stabilizes many APIs"?

**Comment by nasa42** [comment]
Done. Thanks @llogiq!

**Comment by llogiq** [comment]
My pleasure.

**Comment by brson** [comment]
[Deployed!](http://this-week-in-rust.org/blog/2015/09/14/this-week-in-rust-96/)

**Pull request merged**
