### PR TITLE
Add blog post containing video

### PR DESCRIPTION
**Pull request by neosilky**

### CODE REVIEW

**Comment by nasa42** [comment]
I'd suggest to add it to next week's draft.

**Comment by neosilky** [comment]
It was published on Apr 29 -- that's why I put it here. I can add to the draft for next week though, if you'd prefer that. :)

**Comment by nasa42** [comment]
Go for it.

**Comment by neosilky** [comment]
Hey @nasa42, sorry for the late reply.

I've pushed the amended commit. Should be good to go!

**Comment by nasa42** [comment]
Hi @neosilky, I looked at the video. It's quite cool but doesn't seem to be informative. I'm uncertain if the community would find it useful. Maybe add a blog post with your technical analysis?

I do however suggest you to post it to https://www.reddit.com/r/rust/

Also, update us when you release your interactive web page on dependency graphs. That seems interesting!

**Pull request closed without merging**
