### PR TITLE
Add blog post

### PR DESCRIPTION
**Pull request by bishtpawan**
Adding blog "Embody System Commands in Rust Programming"

Thanks

### CODE REVIEW

**Comment by nasa42** [comment]
I'd suggest to post this on [r/rust subreddit](https://www.reddit.com/r/rust) for scrutiny. And if received positively, I'd be happy to include it!

**Comment by bishtpawan** [comment]
Please find r/rust subreddit link [https://www.reddit.com/r/rust/comments/b0lps0/embody_system_commands_in_rust_programming/]

**Comment by nasa42** [comment]
It seems like the Reddit post was removed. I'd suggest to get in touch with subreddit mods to understand their rationale.
I'll close this for now. Please feel free to re-submit after considering my suggestions above.

**Comment by bishtpawan** [comment]
Sure!

**Pull request closed without merging**
