### PR TITLE
TWiR Release 95 (7 September 2015).

### PR DESCRIPTION
**Pull request by nasa42**
/cc @brson @llogiq

### CODE REVIEW

**Comment by nasa42** [comment]
We are slightly low on content this week.
Also, from this week I'm planning to watch Rust development more closely and write a section on "what's new in Rust".

**Comment by llogiq** [comment]
:+1:

**Comment by brson** [comment]
Thanks @nasa42 and @llogic!

I am strangely without access to my ssh keys until sometime tuesday, so I'll ping @cmr to see if he can deploy today.

**Comment by brson** [comment]
I'm going to submit a PR with some additional content in a bit.

**Comment by brson** [comment]
Here's my followup PR https://github.com/cmr/this-week-in-rust/pull/113

**Pull request merged**
