### PR TITLE
Add blog post

### PR DESCRIPTION
**Pull request by bishtpawan**
Adding blog "Frame Cease-less User-Interactive Concept in Rust Programming "

Thanks

### CODE REVIEW

**Comment by nasa42** [comment]
I'd suggest to post this on [r/rust subreddit](https://www.reddit.com/r/rust) for scrutiny. And if received positively, I'd be happy to include it!

**Comment by bishtpawan** [comment]
Hi, I've posted my blog on (r/rust subreddit). Thank you

**Comment by nasa42** [comment]
Could you please link to it? I am unable to find it on the r/rust subreddit.

**Comment by bishtpawan** [comment]
https://www.reddit.com/r/rust/comments/axx9kx/frame_ceaseless_userinteractive_concept_in_rust/

**Comment by nasa42** [comment]
It seems to be removed, though I'm not sure why. Presumably because your account is new and/or you submitted a text post while the post was just a link.
I'd suggest to wait for a mod to take a look at this, failing which, I'd suggest to re-post through "submit a link" (and not through "submit a text post").

**Comment by bishtpawan** [comment]
Yes, it was a text post, I've re-post it through "submit a link" with this link (https://www.reddit.com/r/rust/comments/axxmmn/frame_ceaseless_userinteractive_concept_in_rust/).

**Comment by bishtpawan** [comment]
Hi, I've updated my post again with this link (https://www.reddit.com/r/rust/comments/ayopnv/frame_ceaseless_userinteractive_concept_in_rust/) but I'm not getting any response for my post on Reddit.

**Comment by nasa42** [comment]
The published [reddit link](https://www.reddit.com/r/rust/comments/axxmmn/frame_ceaseless_userinteractive_concept_in_rust/) seems to have received negative total votes (total upvote is less than 50%), which likely suggests that blog post may not meet expected quality standards of community and/or may have technical inaccuracies. As such, it may not be a good fit for TWiR.

To improve technical quality of future articles, I'd suggest to get them proof-edited by colleagues. I'd also recommend to continue submitting your future articles to [Rust subreddit](https://www.reddit.com/r/rust/) to get critical feedback from Rust community. :+1:

**Comment by bishtpawan** [comment]
Hi, actually that post did not get any response from Reddit but when I post
it with my different account then it got some responses so  kindly have a
look on it. In this link [
https://www.reddit.com/r/rust/comments/b4u0k4/frame_ceaseless_userinteractive_concept_in_rust/].
Thank You

**Pull request closed without merging**
