### PR TITLE
Add an new Meili blog post

### PR DESCRIPTION
**Pull request by Kerollmops**
https://blog.meilisearch.com/search-rust-crates-meili/

Thanks and sorry for the previous PR (#1066). I am a little bit dumb :)

### CODE REVIEW

**Comment by nasa42** [comment]
Could you please PR it against today's issue, that way I can get it included to the issue which is just published.

**Comment by Kerollmops** [comment]
You mean, push for on #1066 ? Unfortunately I just deleted the repository associated with it.

**Comment by nasa42** [comment]
I mean making a change in file https://github.com/cmr/this-week-in-rust/blob/master/content/2019-11-12-this-week-in-rust.md in this PR.

**Comment by Kerollmops** [comment]
Fixed, thank you !

**Pull request merged**
