### PR TITLE
Add Blog Post

### PR DESCRIPTION
**Pull request by bishtpawan**
Adding blog "Containerize Rust Application with Docker"

Thanks

### CODE REVIEW

**Comment by nasa42** [comment]
I'd suggest to post this on [r/rust subreddit](https://www.reddit.com/r/rust) for scrutiny. And if received positively, I'd be happy to include it!

**Comment by bishtpawan** [comment]
https://www.reddit.com/r/rust/comments/b4u0k4/frame_ceaseless_userinteractive_concept_in_rust/
I've received some feedbacks from r/rust community. So consider this blog
for this week
https://github.com/cmr/this-week-in-rust/pull/842

**Comment by bishtpawan** [comment]
Here is the link of subreddit of this PR https://www.reddit.com/r/rust/comments/bat1g5/containerize_rust_application_with_docker/

**Comment by nasa42** [comment]
It seems like your post was again flagged as spam and removed. I'd recommend to contact subreddit mods to ask why this action was taken (you can find their usernames in the subreddit sidebar).
Once resolved, you should reopen this PR against newest draft. Thanks!

**Pull request closed without merging**
