### PR TITLE
Blog post rusts hidden talents

### PR DESCRIPTION
**Pull request by dns2utf8**

### CODE REVIEW

**Comment by nasa42** [comment]
I'd suggest to post these on [r/rust subreddit](https://www.reddit.com/r/rust) for scrutiny. And if received positively, I'd be happy to include it!

Also, I'd suggest to rename the submitted title of post to be more descriptive of what the post is about.

**Comment by dns2utf8** [comment]
Hi

I don't have an account on reddit. Is this the process now?

As for the title, have you a suggestion?

**Comment by dns2utf8** [comment]
Anyhow, I made an account for this and posted [the link](https://www.reddit.com/r/rust/comments/byz34r/rusts_hidden_talents_toolchain_and_build_speed/)

**Comment by nasa42** [comment]
> Is this the process now?

Rust community at reddit can do a far better quality check than I can with my limited knowledge of Rust. :slightly_smiling_face:

**Comment by dns2utf8** [comment]
I added some feedback from the community. Do you think this is ok now? :)

**Comment by dns2utf8** [comment]
🎉

**Pull request merged**
