### PR TITLE
Add PX8 Rust project

### PR DESCRIPTION
**Pull request by hallucino**

### CODE REVIEW

**Comment by nasa42** [comment]
Hi @hallucino, it's probably a better idea to directly link to issues on which you are expecting participants, rather than a link to the repository.

**Comment by hallucino** [comment]
Yes you're right !

It was most for the 'News & Blog Posts', is it possible ?

**Comment by nasa42** [comment]
We try to avoid announcing new crates in "News & Blog Posts" section. I'd suggest you to nominate it for [Crate of the Week](https://users.rust-lang.org/t/crate-of-the-week/2704) instead.

**Comment by hallucino** [comment]
Thanks !

**Pull request closed without merging**
