### PR TITLE
add jobs section

### PR DESCRIPTION
**Pull request by oli-obk**
see https://users.rust-lang.org/t/this-week-in-rust-editors-thread/1806/39?u=oli_obk

for now I suggest adding them manually. if it gets more frequent, a thread as suggested by @nasa42 is probably the way to go.

Open question is whether they should get removed in the next or second next issue automatically.

### CODE REVIEW

**Comment by brson** [comment]
Thanks, I'll merge this into this week's posting and add the section to the template. I like the section name. How long do you think we should let these run?

**Comment by oli-obk** [comment]
For my case 2 weeks, or I'll manually ask not to remove it in the PR that would remove it.

**Comment by nasa42** [comment]
Just like we pull events from calendar, maybe we can pull jobs from [weloverustlang.com](http://weloverustlang.com)? I think @zargony maintains it. Pretty empty though atm, but TWiR can help with that.

**Comment by oli-obk** [comment]
that page looks totally broken on my computer...

**Comment by zargony** [comment]
I'm not the maintainer, sorry. I just discovered that site some months ago..

**Comment by oli-obk** [comment]
uhm... Apparently I mis-translated from german. It should be `student research assistant`. Can I update the currently released version of TWIR?

**Pull request merged**
