### PR TITLE
add info

### PR DESCRIPTION
**Pull request by Aimeedeer**
RIB newsletter #4; 
RIB workshop event during SFBW;
Nervos job.

### CODE REVIEW

**Comment by nasa42** [comment]
The article has received negative votes on [reddit](https://www.reddit.com/r/rust/comments/dclvk6/rust_in_blockchain_4_september_2019/), and as such it may not be a notable article for wider Rust community.

Happy to add the event and job listings!

**Comment by brson** [comment]
I don't agree with this reasoning @nasa42. The negative votes are a a reaction from a subset of the Rust community that disagrees with the promotion of Rust as a blockchain programming platform. But the reality is that Rust is _very_ popular as a blockchain programming platform. As responsible stewards following the Rust Code of Conduct we have a responsibility to not discriminate against any segment of our user base.

**Comment by brson** [comment]
Another reason to post this - almost no rust blockchain news gets circulated within the rust community because rust blockchain users _know_ about this discrimination. This newsletter is a single point which _does_ collect that news in order to bring it back into the rust community.

**Comment by brson** [comment]
Sorry for appealing to the code of conduct @nasa42 but this issue of blockchain being quietly ignored by the rust community and the rust project really annoys me.

**Comment by nasa42** [comment]
> As responsible stewards following the Rust Code of Conduct we have a responsibility to not discriminate against any segment of our user base.

I understand your concerns and I definitely do not have any intentions to discriminate against blockchain articles. However I'd also acknowledge that I do need to consider _notability_ of the articles as it would not be possible to include everything. One such (somewhat objective) measure of notability is number of upvotes on reddit, which I've been using to select articles. I understand it's not perfect and I'm open to suggestions.

(I also acknowledge that I've made exceptions for articles in past when authors have made a PR or directly requested on [Twitter](https://twitter.com/ThisWeekInRust), so the rules are a bit blurry (something that I'm hoping to resolve with #1015).)

Having that said, I'm happy to link to next few issues of _Rust in Blockchain_ newsletter which should help in publicising it.

**Pull request merged**
